#!/bin/sh
echo "Content-type: text/html"
echo ""
echo "<head>"
echo "<meta charset=\"utf-8\">"
echo "<title>Документ без названия</title>"
echo "<link href=\"jquery-mobile/jquery.mobile-1.3.0.min.css\" rel=\"stylesheet\" type=\"text/css\">"
echo "<script src=\"jquery-mobile/jquery-1.11.1.min.js\" type=\"text/javascript\"></script>"
echo "<script src=\"jquery-mobile/jquery.mobile-1.3.0.min.js\" type=\"text/javascript\"></script>"
echo "</head>"
echo "<body>"
echo "<div data-role=\"page\" id=\"ini\">"
echo "  <div data-role=\"header\">"
echo "    <h1>Настройка INI файла</h1>"
echo "  </div>"
echo "  <form id=\"forms\" method=\"post\" action=\"javascript:void(null);\" onsubmit=\"call()\">"
echo "  <div data-role=\"fieldcontain\">"
echo "    <label for=\"number\">Период проверки INI файла (сек.):</label>"
echo "    <input name=\"number\" type=\"number\" id=\"number\" value=\"60\"  >"
echo "  </div>"
echo "  <div data-role=\"fieldcontain\">"
echo "    <label for=\"flipswitch4\">Режим работы по датчику:</label>"
echo "    <select name=\"flipswitch4\" id=\"flipswitch4\" data-role=\"slider\">"
echo "      <option value=\"off\">Выкл</option>"
echo "      <option value=\"on\">Вкл.</option>"
echo "    </select>"
echo "  </div>"
echo "  <div data-role=\"fieldcontain\">"
echo "    <label for=\"flipswitch\">Запись снимка (jpeg):</label>"
echo "    <select name=\"flipswitch\" id=\"flipswitch\" data-role=\"slider\">"
echo "      <option value=\"off\">Выкл</option>"
echo "      <option value=\"on\">Вкл.</option>"
echo "    </select>"
echo "  </div>"
echo "  <hr>"
echo "  <div data-role=\"fieldcontain\">"
echo "    <label for=\"flipswitch2\">Запись видео:</label>"
echo "    <select name=\"flipswitch2\" id=\"flipswitch2\" data-role=\"slider\">"
echo "      <option value=\"off\">Выкл</option>"
echo "      <option value=\"on\">Вкл.</option>"
echo "    </select>"
echo "  </div>"
echo "  <div data-role=\"fieldcontain\">"
echo "    <label for=\"number2\">Длина ролика (сек.):</label>"
echo "    <input type=\"number\" name=\"number2\" id=\"number2\" value=\"4\"  >"
echo "  </div>"
echo "  <hr>"
echo "  <div data-role=\"fieldcontain\">"
echo "    <label for=\"flipswitch3\">Режим регистратора:</label>"
echo "    <select name=\"flipswitch3\" id=\"flipswitch3\" data-role=\"slider\">"
echo "      <option value=\"off\">Выкл</option>"
echo "      <option value=\"on\">Вкл.</option>"
echo "    </select>"
echo "  </div>"
echo "  <div data-role=\"fieldcontain\">"
echo "    <label for=\"number3\">Период записи роликов в режиме регистратора (сек.):</label>"
echo "    <input type=\"number\" name=\"number3\" id=\"number3\" value=\"120\" size=\"10\"  >"
echo "  </div>"
echo "  <hr>"
echo "  <div data-role=\"controlgroup\" data-type=\"horizontal\">"
echo "    <input onClick=\"home()\" type=\"button\" value=\"На главную\" data-icon=\"home\" data-iconpos=\"left\" >"
echo "    <input type=\"submit\" value=\"Сохранить\" data-icon=\"arrow-r\" data-iconpos=\"right\""
echo "  </div>"
echo "  </form>"
echo " </div>"
echo " </body>"
echo " <script type=\"text/javascript\" language=\"javascript\">"
echo "     function call() {"
echo "       var msg   = $('#forms').serialize();"
echo "         $.ajax({type: 'POST',url: 'cgi-bin/ini.cgi',data: msg,success: function(data) {$('.results').html(data);},error:  function(xhr, str){alert('???????? ??????: ' + xhr.responseCode);}});"
echo "     }"
echo "    function home() {\"
echo " 	//document.location.href = \"index.html\";"
echo " 	document.location.href = \"cgi-bin/ipcam.cgi\";"
echo " }"
echo " </script>"
echo " </html>"