#!/bin/sh /etc/rc.common

START=99

start () {
	PORT=$(uci -q get 3ginfo.@3ginfo[0].http_port)
	[ -z $PORT ] && { PORT=80; }
	cp /usr/share/3g/recovery.html /usr/share/3g/index.html
	uhttpd -c /usr/share/3g/uhttpd.conf -h /usr/share/3g/ -p 0.0.0.0:$PORT > /dev/null 2>&1
	# httpd_gargoyle -c "cgi-bin/*.sh" -u root -DPF "index.html" -PNF "index.html" -d /usr/share/3ginfo/ -p $PORT > /dev/null 2>&1
}
